const express=require('express');const path=require('path');const bcrypt=require('bcryptjs');const {Pool}=require('pg');const crypto=require('crypto');
const app=express(),PORT=process.env.PORT||3000,DATABASE_URL=process.env.DATABASE_URL;
if(!DATABASE_URL){console.error('Missing DATABASE_URL');process.exit(1)}
const pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const sessions=new Map();app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const email=v=>String(v||'').trim().toLowerCase();
function auth(req,res,next){const t=req.headers.authorization?.replace(/^Bearer\s+/i,'');const e=t&&sessions.get(t);if(!e)return res.status(401).json({error:'Bạn chưa đăng nhập.'});req.email=e;next()}
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name VARCHAR(80) NOT NULL,email VARCHAR(255) UNIQUE NOT NULL,password_hash TEXT NOT NULL,points INT NOT NULL DEFAULT 0,completed_count INT NOT NULL DEFAULT 0,opened_count INT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS tasks(id SERIAL PRIMARY KEY,name VARCHAR(120) NOT NULL,url TEXT NOT NULL,kind VARCHAR(20) NOT NULL DEFAULT 'channel',points INT NOT NULL DEFAULT 5,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE TABLE IF NOT EXISTS completions(id SERIAL PRIMARY KEY,user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,task_id INT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,points INT NOT NULL,completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`);const r=await pool.query('SELECT COUNT(*)::int count FROM tasks');if(!r.rows[0].count){for(const [n,u] of [['@maclaxinh1601','https://www.tiktok.com/@maclaxinh1601'],['@uyn.uyn2229','https://www.tiktok.com/@uyn.uyn2229'],['@thuychang612003','https://www.tiktok.com/@thuychang612003'],['@jang.1.4.6','https://www.tiktok.com/@jang.1.4.6'],['@ngocnhu_png','https://www.tiktok.com/@ngocnhu_png'],['@thao.vo221','https://www.tiktok.com/@thao.vo221'],['@vaycongsono1','https://www.tiktok.com/@vaycongsono1'],['@.trang5689','https://www.tiktok.com/@.trang5689']])await pool.query("INSERT INTO tasks(name,url,kind,points) VALUES($1,$2,'channel',5)",[n,u]);}}
app.get('/api/health',async(_,res)=>{try{await pool.query('SELECT 1');res.json({ok:true})}catch{res.status(500).json({ok:false})}});
app.post('/api/register',async(req,res)=>{try{const n=String(req.body.name||'').trim(),e=email(req.body.email),p=String(req.body.password||'');if(n.length<2||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e)||p.length<6)return res.status(400).json({error:'Thông tin đăng ký không hợp lệ.'});const h=await bcrypt.hash(p,12),r=await pool.query('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email,points',[n,e,h]),t=crypto.randomBytes(32).toString('hex');sessions.set(t,e);res.json({token:t,user:r.rows[0]})}catch(x){if(x.code==='23505')return res.status(409).json({error:'Email đã tồn tại.'});res.status(500).json({error:'Không thể tạo tài khoản.'})}});
app.post('/api/login',async(req,res)=>{try{const e=email(req.body.email),p=String(req.body.password||''),r=await pool.query('SELECT * FROM users WHERE email=$1',[e]);if(!r.rows[0]||!(await bcrypt.compare(p,r.rows[0].password_hash)))return res.status(401).json({error:'Email hoặc mật khẩu không đúng.'});const t=crypto.randomBytes(32).toString('hex');sessions.set(t,e);const u=r.rows[0];res.json({token:t,user:{id:u.id,name:u.name,email:u.email,points:u.points}})}catch{res.status(500).json({error:'Không thể đăng nhập.'})}});
app.post('/api/logout',auth,(req,res)=>{const t=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(t)sessions.delete(t);res.json({ok:true})});
app.get('/api/me',auth,async(req,res)=>{const r=await pool.query('SELECT id,name,email,points,completed_count,opened_count FROM users WHERE email=$1',[req.email]);res.json({user:r.rows[0]})});
app.get('/api/tasks/random',auth,async(_,res)=>{const r=await pool.query('SELECT id,name,url,kind,points FROM tasks WHERE active=true ORDER BY RANDOM() LIMIT 1');if(!r.rows[0])return res.status(404).json({error:'Kho nhiệm vụ đang trống.'});res.json({task:r.rows[0]})});
app.post('/api/tasks/:id/open',auth,async(req,res)=>{const id=Number(req.params.id);const r=await pool.query('SELECT id FROM tasks WHERE id=$1 AND active=true',[id]);if(!r.rows[0])return res.status(404).json({error:'Nhiệm vụ không tồn tại.'});await pool.query('UPDATE users SET opened_count=opened_count+1 WHERE email=$1',[req.email]);res.json({ok:true})});
app.post('/api/tasks/:id/complete',auth,async(req,res)=>{const id=Number(req.params.id),c=await pool.connect();try{await c.query('BEGIN');const u=await c.query('SELECT id FROM users WHERE email=$1 FOR UPDATE',[req.email]),t=await c.query('SELECT id,points FROM tasks WHERE id=$1 AND active=true',[id]);if(!u.rows[0]||!t.rows[0]){await c.query('ROLLBACK');return res.status(404).json({error:'Nhiệm vụ không tồn tại.'})}const d=await c.query('SELECT id FROM completions WHERE user_id=$1 AND task_id=$2 AND completed_at>=CURRENT_DATE LIMIT 1',[u.rows[0].id,id]);if(d.rows[0]){await c.query('ROLLBACK');return res.status(409).json({error:'Bạn đã hoàn thành nhiệm vụ này hôm nay.'})}const pts=Math.max(1,Math.min(100,Number(t.rows[0].points)||5));await c.query('INSERT INTO completions(user_id,task_id,points) VALUES($1,$2,$3)',[u.rows[0].id,id,pts]);const up=await c.query('UPDATE users SET points=points+$1,completed_count=completed_count+1 WHERE id=$2 RETURNING points,completed_count',[pts,u.rows[0].id]);await c.query('COMMIT');res.json({ok:true,pointsAdded:pts,user:up.rows[0]})}catch(e){await c.query('ROLLBACK');res.status(500).json({error:'Không thể ghi nhận nhiệm vụ.'})}finally{c.release()}});
for(const period of ['day','week'])app.get('/api/leaderboard/'+period,async(_,res)=>{const cond=period==='day'?'c.completed_at>=CURRENT_DATE':'c.completed_at>=date_trunc(\'week\',CURRENT_DATE)';const r=await pool.query(`SELECT u.id,u.name,COALESCE(SUM(c.points),0)::int points FROM users u LEFT JOIN completions c ON c.user_id=u.id AND ${cond} GROUP BY u.id,u.name ORDER BY points DESC,u.id LIMIT 50`);res.json({leaderboard:r.rows})});
function admin(req,res,next){if(email(process.env.ADMIN_EMAIL)!==email(req.email))return res.status(403).json({error:'Không có quyền quản trị.'});next()}
app.get('/api/admin/tasks',auth,admin,async(_,res)=>res.json({tasks:(await pool.query('SELECT id,name,url,kind,points,active FROM tasks ORDER BY id DESC')).rows}));
app.post('/api/admin/tasks',auth,admin,async(req,res)=>{const n=String(req.body.name||'').trim(),u=String(req.body.url||'').trim(),k=req.body.kind==='video'?'video':'channel',p=Math.max(1,Math.min(100,Number(req.body.points)||5));if(!n||!/^https:\/\/(www\.)?tiktok\.com\/(?:@|video\/)/i.test(u))return res.status(400).json({error:'Tên hoặc link TikTok không hợp lệ.'});const r=await pool.query('INSERT INTO tasks(name,url,kind,points) VALUES($1,$2,$3,$4) RETURNING *',[n,u,k,p]);res.json({task:r.rows[0]})});
app.delete('/api/admin/tasks/:id',auth,admin,async(req,res)=>{await pool.query('UPDATE tasks SET active=false WHERE id=$1',[Number(req.params.id)]);res.json({ok:true})});
app.get('*',(_,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
init().then(()=>app.listen(PORT,()=>console.log('nhiemvutiktokfree running on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
